name: oauthproject
description: Oauth Test Project
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  oauth2_client: ^3.2.2
  shared_preferences: ^2.2.1
  dio: ^5.3.2
  jwt_decoder: ^2.0.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
