// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPItscoU25BEvAEbgmUtc3lX25MS562r4',
    appId: '1:91373226635:web:78df92480b9c49fbf9628e',
    messagingSenderId: '91373226635',
    projectId: 'fallen-harbour-flyer',
    authDomain: 'fallen-harbour-flyer.firebaseapp.com',
    storageBucket: 'fallen-harbour-flyer.appspot.com',
    measurementId: 'G-SBZEP990YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUvDZ4TF5F7WVy_01xzbEVdnbCme0f0I',
    appId: '1:91373226635:android:ae99d63be0067972f9628e',
    messagingSenderId: '91373226635',
    projectId: 'fallen-harbour-flyer',
    storageBucket: 'fallen-harbour-flyer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLfafa8UAyhNxCxBypb3sqcAkUhTCXRwU',
    appId: '1:91373226635:ios:6535e96fe219a4fcf9628e',
    messagingSenderId: '91373226635',
    projectId: 'fallen-harbour-flyer',
    storageBucket: 'fallen-harbour-flyer.appspot.com',
    iosBundleId: 'com.example.oauthproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLfafa8UAyhNxCxBypb3sqcAkUhTCXRwU',
    appId: '1:91373226635:ios:105e72dfbc75674df9628e',
    messagingSenderId: '91373226635',
    projectId: 'fallen-harbour-flyer',
    storageBucket: 'fallen-harbour-flyer.appspot.com',
    iosBundleId: 'com.example.oauthproject.RunnerTests',
  );
}
